# Generated by Django 6.0.1 on 2026-01-13 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('quizzes', '0001_initial'), ('quizzes', '0002_alter_answer_question_fk_alter_question_quiz_fk_and_more'), ('quizzes', '0003_quizattempt_userresponse'), ('quizzes', '0004_quizattempt_is_force_completed_and_more'), ('quizzes', '0005_alter_answer_options_alter_question_options')]

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('multiple', 'Multiple Choice'), ('single', 'Single Choice')], max_length=8, verbose_name='question type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=120, verbose_name='response')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is correct')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('question_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('module_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.module')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quiz_fk', 'order'), name='unique_quiz_fk_order'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz', verbose_name='quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='module_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='modules.module', verbose_name='module'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UID')),
                ('score', models.FloatField(default=0.0, verbose_name='score')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is completed')),
                ('quiz_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='quizzes.quiz', verbose_name='quiz')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('is_force_completed', models.BooleanField(default=False, verbose_name='is completed force')),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True, null=True, verbose_name='response text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is correct')),
                ('points_awarded', models.FloatField(default=0.0, verbose_name='points awarded')),
                ('attempt_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='quizzes.quizattempt', verbose_name='user response')),
                ('question_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='quizzes.question', verbose_name='question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_responses', to='quizzes.answer', verbose_name='selected choices')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='selected_in_multiple_responses', to='quizzes.answer')),
            ],
            options={
                'verbose_name': 'User Response',
                'verbose_name_plural': 'User Responses',
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['order'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
