# Generated by Django 6.0.1 on 2026-01-18 15:35

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_squashed_0005_alter_answer_options_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description'),
        ),
    ]
