# Generated by Django 6.0.1 on 2026-01-30 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_alter_quiz_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResultMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is correct?')),
            ],
            options={
                'verbose_name': 'Question result message',
                'verbose_name_plural': 'Question result messages',
            },
        ),
        migrations.AddConstraint(
            model_name='userresponse',
            constraint=models.UniqueConstraint(fields=('attempt_fk', 'question_fk'), name='unique_attempt_question_response'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_correct': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_for_questions', to='quizzes.questionresultmessagetemplate', verbose_name='correct answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='incorrect_answer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_correct': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incorrect_for_questions', to='quizzes.questionresultmessagetemplate', verbose_name='incorrect answer'),
        ),
    ]
