# Generated by Django 6.0.1 on 2026-02-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_questionresultmessagetemplate_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='unique_quiz_fk_order',
        ),
    ]
