# Generated by Django 6.0.1 on 2026-02-01 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_lesson_audio_url_lesson_score_and_more'),
        ('quizzes', '0007_questionresultmessagetemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='module_fk',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='lesson_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.lesson', verbose_name='Context Lesson'),
        ),
    ]
