# Generated by Django 6.0.1 on 2026-02-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_remove_question_unique_quiz_fk_order'),
        ('quizzes', '0008_remove_quiz_module_fk_quizattempt_lesson_context'),
    ]

    operations = [
    ]
