# Generated by Django 6.0.2 on 2026-02-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_merge_20260202_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
    ]
