# Generated by Django 6.0.1 on 2026-02-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_alter_answer_order_alter_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(max_length=200, verbose_name='title'),
        ),
    ]
