# Generated by Django 6.0.2 on 2026-02-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_alter_question_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Quiz Attempt', 'verbose_name_plural': 'Quiz Attempts'},
        ),
    ]
