# Generated by Django 6.0.1 on 2026-01-17 09:08

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        ('quizzes', '0001_squashed_0005_alter_answer_options_alter_question_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('quiz', 'Quiz'), ('homework', 'Homework')], max_length=120, verbose_name='content type')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='video url')),
                ('text_content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='text content')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('module_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='modules.module', verbose_name='Module')),
                ('quiz_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='quizzes.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('module_fk', 'order'), name='unique_module_lesson_order')],
            },
        ),
    ]
