# Generated by Django 6.0.1 on 2026-01-20 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_module_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is completed')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='completed at')),
                ('lesson_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='modules.lesson', verbose_name='Lesson')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Lesson Progress',
                'verbose_name_plural': 'User Lesson Progresses',
                'constraints': [models.UniqueConstraint(fields=('user_fk', 'lesson_fk'), name='unique_user_lesson_progress')],
            },
        ),
    ]
