# Generated by Django 6.0.1 on 2026-01-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_alter_module_options_module_order'),
        ('modules', '0004_userlessonprogress'),
    ]

    operations = [
    ]
