# Generated by Django 6.0.1 on 2026-01-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_merge_20260123_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_scored',
            field=models.BooleanField(default=True, verbose_name='is scored'),
        ),
    ]
