# Generated by Django 6.0.1 on 2026-02-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_merge_20260123_2208'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lesson',
            name='unique_module_lesson_order',
        ),
    ]
