# Generated by Django 6.0.1 on 2026-02-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_module_is_scored'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audio_url',
            field=models.URLField(blank=True, null=True, verbose_name='audio url'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('audio', 'Audio'), ('quiz', 'Quiz'), ('homework', 'Homework')], max_length=120, verbose_name='content type'),
        ),
    ]
