# Generated by Django 6.0.1 on 2026-02-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_remove_lesson_unique_module_lesson_order'),
        ('modules', '0007_lesson_audio_url_lesson_score_and_more'),
    ]

    operations = [
    ]
