# Generated by Django 6.0.2 on 2026-02-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_merge_20260202_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
    ]
