# Generated by Django 6.0.2 on 2026-02-08 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_alter_module_order'),
        ('quizzes', '0009_merge_20260202_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='quiz_fk',
            field=models.ForeignKey(blank=True, limit_choices_to={'lessons__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='quizzes.quiz', verbose_name='Quiz'),
        ),
    ]
