# Generated by Django 6.0.2 on 2026-02-09 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_alter_lesson_quiz_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audio_url',
            field=models.FileField(blank=True, null=True, upload_to='audio', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'm4a', 'wav', 'ogg'])], verbose_name='audio url'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])], verbose_name='video url'),
        ),
    ]
