# Generated by Django 6.0.2 on 2026-02-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_alter_lesson_audio_url_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='score'),
        ),
    ]
