# Generated by Django 6.0.1 on 2026-02-14 23:13

import django.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_alter_lesson_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audio_url',
            field=models.FileField(blank=True, help_text='Allowed formats', null=True, upload_to='audio', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'm4a', 'wav', 'ogg'])], verbose_name='audio url'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.FileField(blank=True, help_text='Allowed formats', null=True, upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])], verbose_name='video url'),
        ),
    ]
