# Generated by Django 6.0.2 on 2026-02-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0014_lesson_is_active_module_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
    ]
