# Generated by Django 6.0.2 on 2026-02-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0015_alter_lesson_order_alter_module_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
    ]
