# Generated by Django 6.0.1 on 2026-02-05 00:44

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('additional_content', tinymce.models.HTMLField(verbose_name='Additional Content')),
            ],
            options={
                'verbose_name': 'Mental Health',
                'verbose_name_plural': 'Mental Health',
            },
        ),
        migrations.CreateModel(
            name='MentalHealthAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, 'Before start education'), (2, 'After finish education')], verbose_name='number')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('mental_health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mental_health.mentalhealth', verbose_name='mental health')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mental_health_attempts', to=settings.AUTH_USER_MODEL, verbose_name='mental health')),
            ],
            options={
                'verbose_name': 'mental health attempt',
                'verbose_name_plural': 'mental health attempts',
            },
        ),
        migrations.CreateModel(
            name='MentalHealthQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question text')),
                ('min_score', models.PositiveIntegerField(default=0, verbose_name='minimum score')),
                ('max_score', models.PositiveIntegerField(default=5, verbose_name='maximum score')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('mental_health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mental_health.mentalhealth', verbose_name='mental health')),
            ],
            options={
                'verbose_name': 'mental health question',
                'verbose_name_plural': 'mental health questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserMentalHealthResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.PositiveIntegerField(default=0, verbose_name='response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('attempt_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mental_health_responses', to='mental_health.mentalhealthattempt', verbose_name='mental health')),
                ('question_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mental_health_responses', to='mental_health.mentalhealthquestion', verbose_name='mental health')),
            ],
            options={
                'verbose_name': 'mental health user mental health response',
                'verbose_name_plural': 'mental health user mental health responses',
            },
        ),
    ]
