# Generated by Django 6.0.1 on 2026-02-06 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mentalhealthattempt',
            constraint=models.UniqueConstraint(fields=('user_fk', 'number'), name='unique_user_number_mental_health'),
        ),
    ]
