# Generated by Django 6.0.2 on 2026-02-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0002_mentalhealthattempt_unique_user_number_mental_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalhealthquestion',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
    ]
