# Generated by Django 6.0.1 on 2026-01-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='score'),
        ),
    ]
