# Generated by Django 6.0.1 on 2026-01-22 02:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_membership', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Group Membership',
                'verbose_name_plural': 'Group Memberships',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UID')),
                ('label', models.CharField(blank=True, help_text='For internal use only. This label is not displayed on the user page', max_length=255, null=True, verbose_name='label')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('registration_started_at', models.DateTimeField(verbose_name='registration started at')),
                ('registration_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='registration finished at')),
                ('course_started_at', models.DateTimeField(verbose_name='course started at')),
                ('opening_interval_days', models.PositiveIntegerField(default=7, help_text='Value for the interval (in days) for opening modules for the current group', verbose_name='Opening interval in days')),
                ('users', models.ManyToManyField(blank=True, help_text='Select active users for this group.', related_name='user_groups', through='users.GroupMembership', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name': 'User Group',
                'verbose_name_plural': 'User Groups',
                'ordering': ['registration_started_at'],
            },
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='users.usergroup', verbose_name='group'),
        ),
    ]
