# Generated by Django 6.0.1 on 2026-01-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_groupmembership_usergroup_groupmembership_group'),
        ('users', '0004_user_score'),
    ]

    operations = [
    ]
