# Generated by Django 6.0.1 on 2026-01-30 22:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20260123_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_group',
            field=models.CharField(choices=[('under_24', 'Under 24'), ('25_44', '25-44'), ('45_plus', '45+')], default='under_24', max_length=20, verbose_name='age group'),
        ),
        migrations.AddField(
            model_name='user',
            name='children',
            field=models.CharField(blank=True, choices=[('yes_under_5', 'Yes, under 5 years'), ('yes_6_18', 'Yes, 6-18 years'), ('yes_18_plus', 'Yes, 18+'), ('no', 'No'), ('prefer_not_to_say', 'Prefer not to say')], max_length=30, null=True, verbose_name='children'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=150, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='user',
            name='family_status',
            field=models.CharField(blank=True, choices=[('in_relationship_or_married', 'In a relationship / Married'), ('not_in_relationship', 'Not in a relationship'), ('divorcing_or_divorced', 'Divorcing / Divorced'), ('prefer_not_to_say', 'Prefer not to say')], max_length=40, null=True, verbose_name='family status'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('non_binary', 'Non-binary / Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=30, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('mental_health', 'Mental health and self-care'), ('relationships', 'Relationships and family'), ('parenting', 'Parenting'), ('self_development', 'Self-development and learning'), ('career', 'Work / Career'), ('creativity', 'Creativity'), ('physical_health', 'Physical health and movement'), ('spirituality', 'Spirituality / Meanings'), ('hobbies', 'Rest and hobbies'), ('prefer_not_to_say', 'Prefer not to say')], max_length=50), blank=True, default=list, verbose_name='interests'),
        ),
        migrations.AddField(
            model_name='user',
            name='interests_other',
            field=models.CharField(blank=True, max_length=255, verbose_name='other interests'),
        ),
    ]
