# Generated by Django 6.0.1 on 2026-02-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_age_group_user_children_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_approved_requirements',
            field=models.BooleanField(default=False, verbose_name='has approved requirements'),
        ),
    ]
