# Generated by Django 6.0.1 on 2026-02-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_has_approved_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('general', 'General'), ('under_24', 'Under 24'), ('25_44', '25-44'), ('45_plus', '45+')], max_length=20, unique=True, verbose_name='audience')),
                ('chat_title', models.CharField(max_length=255, verbose_name='chat title')),
                ('invite_link', models.URLField(help_text='Example: https://t.me/', max_length=500, verbose_name='invite link')),
                ('custom_invite_message', models.CharField(max_length=255, verbose_name='custom invite message')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Chat Invitation',
                'verbose_name_plural': 'Chat Invitations',
                'ordering': ['audience', '-created_at'],
            },
        ),
    ]
