# Generated by Django 6.0.2 on 2026-02-19 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_chatinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('os_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='OS name')),
                ('browser', models.CharField(blank=True, max_length=255, null=True, verbose_name='browser')),
                ('device_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='device type')),
                ('raw_user_agent', models.TextField(blank=True, null=True, verbose_name='raw user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_log', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Device Log',
                'verbose_name_plural': 'User Device Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
