# Generated by Django 6.0.2 on 2026-02-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userdevicelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinvitation',
            name='invite_link',
            field=models.URLField(max_length=500, verbose_name='invite link'),
        ),
    ]
