# Generated by Django 6.0.1 on 2026-02-23 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_chatinvitation_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinvitation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_invitations', to='users.usergroup', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='chatinvitation',
            name='audience',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('under_24', 'Under 24'), ('25_44', '25-44'), ('45_plus', '45+')], max_length=20, null=True, verbose_name='audience'),
        ),
        migrations.AddConstraint(
            model_name='chatinvitation',
            constraint=models.UniqueConstraint(fields=('group', 'audience'), name='unique_audience_per_group'),
        ),
    ]
