# Generated by Django 6.0.1 on 2026-02-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_chatinvitation_group_alter_chatinvitation_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinvitation',
            name='audience',
            field=models.CharField(choices=[('general', 'General'), ('under_24', 'Under 24'), ('25_44', '25-44'), ('45_plus', '45+')], max_length=20, null=True, verbose_name='audience'),
        ),
    ]
