# Generated by Django 6.0.1 on 2026-01-17 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homeworks', '0001_initial'),
        ('modules', '0002_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='lesson_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='modules.lesson', verbose_name='lesson'),
        ),
    ]
