# Generated by Django 6.0.1 on 2026-01-18 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(verbose_name='answer')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='feedback')),
                ('is_approved', models.BooleanField(default=False, verbose_name='is approved')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='date sent')),
                ('date_review', models.DateTimeField(blank=True, null=True, verbose_name='date reviewed')),
                ('homework_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='homeworks.homework', verbose_name='homework')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Homework',
                'verbose_name_plural': 'User Homeworks',
                'constraints': [models.UniqueConstraint(fields=('user_fk', 'homework_fk'), name='unique_user_homework')],
            },
        ),
    ]
