# Generated by Django 6.0.1 on 2026-01-18 16:19

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0003_usersubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_auto_approved',
            field=models.BooleanField(default=False, verbose_name='is auto-approved'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description'),
        ),
    ]
