# Generated by Django 6.0.2 on 2026-02-09 12:16

import apps.homeworks.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0004_homework_is_auto_approved_alter_homework_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='file_answer',
            field=models.FileField(blank=True, null=True, upload_to=apps.homeworks.utils.upload_homework_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt'])], verbose_name='file answer'),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='text_answer',
            field=models.TextField(blank=True, null=True, verbose_name='answer'),
        ),
    ]
