# Generated by Django 6.0.2 on 2026-02-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0005_usersubmission_file_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='is_auto_approved',
            field=models.BooleanField(default=True, verbose_name='is auto-approved'),
        ),
    ]
