# Generated by Django 6.0.2 on 2026-02-17 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('homeworks', '0007_alter_homework_lesson_fk'), ('homeworks', '0008_alter_homework_lesson_fk')]

    dependencies = [
        ('homeworks', '0006_alter_homework_is_auto_approved'),
        ('modules', '0017_alter_lesson_order_alter_module_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='lesson_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='modules.lesson', verbose_name='lesson'),
        ),
    ]
