# Generated by Django 6.0.1 on 2026-02-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0007_alter_homework_lesson_fk_squashed_0008_alter_homework_lesson_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubmission',
            old_name='date_sent',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
